PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX gcis: <https://data.globalchange.gov/gcis.owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX db: <http://dbpedia.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT
?platform_gcis
?platform_dbpedia 
?launchDate_gcis
?launchDate_dbpedia 
?cospar_dbpedia
WHERE {
  FILTER(str(?match) = str(?platform_dbpedia))
  SERVICE <http://data.globalchange.gov/sparql> {
    ?platform_gcis a gcis:Platform .
    ?platform_gcis owl:sameAs ?match .
    ?platform_gcis dbp:launchDate ?launchDate_gcis
    FILTER regex(?match, "dbpedia.org", "i") .
  }
  SERVICE <http://dbpedia.org/sparql> {
    ?platform_dbpedia dbp:launchDate ?launchDate_dbpedia .
    OPTIONAL { ?platform_dbpedia dbp:cosparId ?cospar_dbpedia }
  }
} LIMIT 60
