#!/bin/bash

# Usage:
#
# ./sparql-to-csv <filename.sparql>
# ./sparql-to-csv <filename.sparql> > filename.csv
#

host=https://data.globalchange.gov/sparql
q="`cat ${1:-/dev/stdin}`"

curl -s -G --data-urlencode "format=text/csv" --data-urlencode "query=$q" $host

