PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gcis: <http://data.globalchange.gov/gcis.owl#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT
    DISTINCT ?finding, ?journal
FROM <http://data.globalchange.gov>
WHERE {
  <http://data.globalchange.gov/report/nca3> gcis:hasChapter ?chapter .
  <http://data.globalchange.gov/report/nca3> gcis:hasFinding ?finding .
  OPTIONAL{ ?chapter gcis:hasFinding ?finding .}
  ?finding cito:cites ?publication .
  ?publication dcterms:isPartOf ?journal .
  FILTER (regex(?journal, "nature", "i") || regex(?journal, "^http://data.globalchange.gov/journal/science$", "i"))
}
