PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX gcis: <http://data.globalchange.gov/gcis.owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dbpprop: <http://dbpedia.org/property/>

SELECT ?s ?lauchDate ?deactivated
FROM <http://data.globalchange.gov>
WHERE {
  ?s a gcis:Platform .
  OPTIONAL { ?s dbpprop:deactivated ?deactivated }
  OPTIONAL { ?s dbpprop:launchDate ?lauchDate }
}

