PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX gcis: <http://data.globalchange.gov/gcis.owl#>

select distinct ?dataset
?instrument_instance
where {
    ?dataset a gcis:Dataset .
  { ?dataset prov:wasAttributedTo ?instrument_instance } UNION { ?dataset prov:wasDerivedFrom ?instrument_instance } .
    ?instrument_instance a gcis:Instrument .
}
